apiVersion: v1
kind: Service
metadata:
  name:  {{ template "volantmq.fullname" . }}
  labels:
    app: {{ template "volantmq.name" . }}
    chart: {{ template "volantmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: {{ template "volantmq.name" . }}
    release: {{ .Release.Name }}